// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtoobkVOlq6YwcqtDCgUDFvjzUkJO2-MY',
    appId: '1:92598060179:web:f836bdcad690856f9c7966',
    messagingSenderId: '92598060179',
    projectId: 'applamdep-ffa8e',
    authDomain: 'applamdep-ffa8e.firebaseapp.com',
    storageBucket: 'applamdep-ffa8e.firebasestorage.app',
    measurementId: 'G-7XR0JZ1DND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStDSAI_yc0qS_8VmGPMcm4RGAtfeq3tI',
    appId: '1:92598060179:android:f399fc7a0fd9fde79c7966',
    messagingSenderId: '92598060179',
    projectId: 'applamdep-ffa8e',
    storageBucket: 'applamdep-ffa8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAQhv6C8BFI0mkwMidX8JhEV1Is9TJA7s',
    appId: '1:92598060179:ios:607cf854ebe76c6e9c7966',
    messagingSenderId: '92598060179',
    projectId: 'applamdep-ffa8e',
    storageBucket: 'applamdep-ffa8e.firebasestorage.app',
    iosClientId: '92598060179-tfgcvaja80g0nu11cm744d1v2beinb5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.applamdep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAQhv6C8BFI0mkwMidX8JhEV1Is9TJA7s',
    appId: '1:92598060179:ios:607cf854ebe76c6e9c7966',
    messagingSenderId: '92598060179',
    projectId: 'applamdep-ffa8e',
    storageBucket: 'applamdep-ffa8e.firebasestorage.app',
    iosClientId: '92598060179-tfgcvaja80g0nu11cm744d1v2beinb5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.applamdep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtoobkVOlq6YwcqtDCgUDFvjzUkJO2-MY',
    appId: '1:92598060179:web:e32fdeb7e332b4f89c7966',
    messagingSenderId: '92598060179',
    projectId: 'applamdep-ffa8e',
    authDomain: 'applamdep-ffa8e.firebaseapp.com',
    storageBucket: 'applamdep-ffa8e.firebasestorage.app',
    measurementId: 'G-B06DP5F5TZ',
  );
}
